#!/bin/bash

cd $(dirname $BASH_SOURCE)
CURRENT_DIR=`pwd`

export GIT_SSL_NO_VERIFY=true

lnif() {
    if [ -e "$1" ]; then
        ln -sf "$1" "$2"
    fi
}


echo "Step1: backing up current vim config"
today=`date +%Y%m%d`
    for i in $HOME/.vim $HOME/.vimrc $HOME/.gvimrc $HOME/.vimrc.bundles; do [ -e $i ] && [ ! -L $i ] && mv $i $i.$today; done
    for i in $HOME/.vim $HOME/.vimrc $HOME/.gvimrc $HOME/.vimrc.bundles; do [ -L $i ] && unlink $i ; done
    for i in $HOME/.config/nvim $HOME/.config/nvim/init.vim; do [ -e $i ] && [ ! -L $i ] && mv $i $i.$today; done
    for i in $HOME/.config/nvim/init.vim $HOME/.config/nvim; do [ -L $i ] && unlink $i ; done

    echo "Step2: setting up symlinks"
    lnif $CURRENT_DIR/vimrc $HOME/.vimrc
    lnif "$CURRENT_DIR/" "$HOME/.vim"
    lnif "$CURRENT_DIR/" "$HOME/.config/nvim"
    lnif $CURRENT_DIR/vimrc $CURRENT_DIR/init.vim

curl --insecure -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim

    echo "Step3: update/install plugins using Vim-plug"
    system_shell=$SHELL
    export SHELL="/bin/sh"
    vim -u $HOME/.vimrc +PlugInstall! +PlugClean! +qall
    export SHELL=$system_shell

  echo  "Install Done!"



